kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: fis-test
  name: fis-test

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: fis-test
  name: role-experiments
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: [ "get", "create", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list", "get", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["pods/ephemeralcontainers"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-role-experiments
  namespace: fis-test
subjects:
- kind: ServiceAccount
  name: fis-test
  namespace: fis-test
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: fis-experiment
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: fis-experiment-group
roleRef:
  kind: Role
  name: role-experiments
  apiGroup: rbac.authorization.k8s.io
